START TRANSACTION;

-- Adiciona as colunas PasswordResetToken e PasswordResetTokenExpires à tabela Usuarios
DO $EF$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Usuarios' AND column_name = 'PasswordResetToken') THEN
        ALTER TABLE "Usuarios" ADD "PasswordResetToken" character varying(255);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Usuarios' AND column_name = 'PasswordResetTokenExpires') THEN
        ALTER TABLE "Usuarios" ADD "PasswordResetTokenExpires" timestamp with time zone;
    END IF;
END $EF$;

-- Cria a tabela Servicos se ela não existir
DO $EF$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'Servicos') THEN
        CREATE TABLE "Servicos" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY,
            "Nome" character varying(100) NOT NULL,
            "Preco" numeric(18,2) NOT NULL,
            "DuracaoMinutos" integer NOT NULL,
            "BarbeariaId" integer NOT NULL,
            CONSTRAINT "PK_Servicos" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_Servicos_Barbearias_BarbeariaId" FOREIGN KEY ("BarbeariaId") REFERENCES "Barbearias" ("Id") ON DELETE CASCADE
        );
        CREATE INDEX "IX_Servicos_BarbeariaId" ON "Servicos" ("BarbeariaId");
    END IF;
END $EF$;

-- Atualiza as colunas existentes para não-nulas e com valor padrão, se necessário
-- Estas alterações são do mesmo arquivo de migração, mas podem já ter sido aplicadas
DO $EF$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Usuarios' AND column_name = 'Foto' AND is_nullable = 'YES') THEN
        UPDATE "Usuarios" SET "Foto" = '' WHERE "Foto" IS NULL;
        ALTER TABLE "Usuarios" ALTER COLUMN "Foto" SET NOT NULL;
        ALTER TABLE "Usuarios" ALTER COLUMN "Foto" SET DEFAULT '';
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Usuarios' AND column_name = 'Especialidades' AND is_nullable = 'YES') THEN
        UPDATE "Usuarios" SET "Especialidades" = '' WHERE "Especialidades" IS NULL;
        ALTER TABLE "Usuarios" ALTER COLUMN "Especialidades" SET NOT NULL;
        ALTER TABLE "Usuarios" ALTER COLUMN "Especialidades" SET DEFAULT '';
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Usuarios' AND column_name = 'Descricao' AND is_nullable = 'YES') THEN
        UPDATE "Usuarios" SET "Descricao" = '' WHERE "Descricao" IS NULL;
        ALTER TABLE "Usuarios" ALTER COLUMN "Descricao" SET NOT NULL;
        ALTER TABLE "Usuarios" ALTER COLUMN "Descricao" SET DEFAULT '';
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Barbearias' AND column_name = 'Logo' AND is_nullable = 'YES') THEN
        UPDATE "Barbearias" SET "Logo" = '' WHERE "Logo" IS NULL;
        ALTER TABLE "Barbearias" ALTER COLUMN "Logo" SET NOT NULL;
        ALTER TABLE "Barbearias" ALTER COLUMN "Logo" SET DEFAULT '';
    END IF;
END $EF$;

-- Registra a migração no histórico do Entity Framework Core
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250907203142_AddPasswordResetToUserFields') THEN
        INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
        VALUES ('20250907203142_AddPasswordResetToUserFields', '8.0.0');
    END IF;
END $EF$;

COMMIT;


