CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250719184728_InitialCreate') THEN
    CREATE TABLE "Barbearias" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" character varying(100) NOT NULL,
        "Endereco" character varying(200) NOT NULL,
        "Telefone" character varying(20) NOT NULL,
        "Email" character varying(100) NOT NULL,
        "Logo" character varying(500),
        "CodigoConvite" character varying(10) NOT NULL,
        "DataCriacao" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Barbearias" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250719184728_InitialCreate') THEN
    CREATE TABLE "Usuarios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" character varying(100) NOT NULL,
        "Email" character varying(100) NOT NULL,
        "SenhaHash" character varying(255) NOT NULL,
        "TipoUsuario" integer NOT NULL,
        "BarbeariaId" integer,
        "Foto" character varying(500),
        "Especialidades" character varying(500),
        "Descricao" character varying(1000),
        "DataCriacao" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Usuarios_Barbearias_BarbeariaId" FOREIGN KEY ("BarbeariaId") REFERENCES "Barbearias" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250719184728_InitialCreate') THEN
    CREATE TABLE "HorariosDisponiveis" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DataHora" timestamp with time zone NOT NULL,
        "BarbeiroId" integer NOT NULL,
        "EstaDisponivel" boolean NOT NULL,
        "DataCriacao" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_HorariosDisponiveis" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_HorariosDisponiveis_Usuarios_BarbeiroId" FOREIGN KEY ("BarbeiroId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250719184728_InitialCreate') THEN
    CREATE TABLE "Agendamentos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ClienteId" integer NOT NULL,
        "BarbeiroId" integer NOT NULL,
        "DataHora" timestamp with time zone NOT NULL,
        "Observacoes" character varying(500),
        "Status" integer NOT NULL,
        "DataCriacao" timestamp with time zone NOT NULL,
        "DataAtualizacao" timestamp with time zone,
        "BarbeariaId" integer NOT NULL,
        "HorarioDisponivelId" integer,
        CONSTRAINT "PK_Agendamentos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Agendamentos_Barbearias_BarbeariaId" FOREIGN KEY ("BarbeariaId") REFERENCES "Barbearias" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Agendamentos_HorariosDisponiveis_HorarioDisponivelId" FOREIGN KEY ("HorarioDisponivelId") REFERENCES "HorariosDisponiveis" ("Id"),
        CONSTRAINT "FK_Agendamentos_Usuarios_BarbeiroId" FOREIGN KEY ("BarbeiroId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Agendamentos_Usuarios_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250719184728_InitialCreate') THEN
    CREATE INDEX "IX_Agendamentos_BarbeariaId_DataHora" ON "Agendamentos" ("BarbeariaId", "DataHora");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250719184728_InitialCreate') THEN
    CREATE INDEX "IX_Agendamentos_BarbeiroId_DataHora" ON "Agendamentos" ("BarbeiroId", "DataHora");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250719184728_InitialCreate') THEN
    CREATE INDEX "IX_Agendamentos_ClienteId" ON "Agendamentos" ("ClienteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250719184728_InitialCreate') THEN
    CREATE INDEX "IX_Agendamentos_HorarioDisponivelId" ON "Agendamentos" ("HorarioDisponivelId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250719184728_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Barbearias_CodigoConvite" ON "Barbearias" ("CodigoConvite");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250719184728_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Barbearias_Email" ON "Barbearias" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250719184728_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_HorariosDisponiveis_BarbeiroId_DataHora" ON "HorariosDisponiveis" ("BarbeiroId", "DataHora");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250719184728_InitialCreate') THEN
    CREATE INDEX "IX_Usuarios_BarbeariaId" ON "Usuarios" ("BarbeariaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250719184728_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Usuarios_Email" ON "Usuarios" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250719184728_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250719184728_InitialCreate', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250803185053_AddMetodoPagamentoToAgendamento') THEN
    ALTER TABLE "Agendamentos" ADD "MetodoPagamento" character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250803185053_AddMetodoPagamentoToAgendamento') THEN
    ALTER TABLE "Agendamentos" ADD "PrecoServico" numeric(10,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250803185053_AddMetodoPagamentoToAgendamento') THEN
    ALTER TABLE "Agendamentos" ADD "TipoServico" character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250803185053_AddMetodoPagamentoToAgendamento') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250803185053_AddMetodoPagamentoToAgendamento', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250819015558_AddCodigoBarbeariaToBarbearias') THEN
    ALTER TABLE "Usuarios" ALTER COLUMN "SenhaHash" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250819015558_AddCodigoBarbeariaToBarbearias') THEN
    ALTER TABLE "Usuarios" ADD "GoogleId" character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250819015558_AddCodigoBarbeariaToBarbearias') THEN
    ALTER TABLE "Barbearias" ADD "CodigoBarbearia" character varying(8) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250819015558_AddCodigoBarbeariaToBarbearias') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250819015558_AddCodigoBarbeariaToBarbearias', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250821020455_AddTelefoneToUsuario') THEN
    ALTER TABLE "Usuarios" ADD "Telefone" character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250821020455_AddTelefoneToUsuario') THEN
    ALTER TABLE "Agendamentos" ALTER COLUMN "TipoServico" TYPE character varying(100);
    UPDATE "Agendamentos" SET "TipoServico" = '' WHERE "TipoServico" IS NULL;
    ALTER TABLE "Agendamentos" ALTER COLUMN "TipoServico" SET NOT NULL;
    ALTER TABLE "Agendamentos" ALTER COLUMN "TipoServico" SET DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250821020455_AddTelefoneToUsuario') THEN
    ALTER TABLE "Agendamentos" ALTER COLUMN "PrecoServico" TYPE numeric;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250821020455_AddTelefoneToUsuario') THEN
    UPDATE "Agendamentos" SET "DataAtualizacao" = TIMESTAMPTZ '-infinity' WHERE "DataAtualizacao" IS NULL;
    ALTER TABLE "Agendamentos" ALTER COLUMN "DataAtualizacao" SET NOT NULL;
    ALTER TABLE "Agendamentos" ALTER COLUMN "DataAtualizacao" SET DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250821020455_AddTelefoneToUsuario') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250821020455_AddTelefoneToUsuario', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250907203142_AddPasswordResetToUserFields') THEN
    UPDATE "Usuarios" SET "Foto" = '' WHERE "Foto" IS NULL;
    ALTER TABLE "Usuarios" ALTER COLUMN "Foto" SET NOT NULL;
    ALTER TABLE "Usuarios" ALTER COLUMN "Foto" SET DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250907203142_AddPasswordResetToUserFields') THEN
    UPDATE "Usuarios" SET "Especialidades" = '' WHERE "Especialidades" IS NULL;
    ALTER TABLE "Usuarios" ALTER COLUMN "Especialidades" SET NOT NULL;
    ALTER TABLE "Usuarios" ALTER COLUMN "Especialidades" SET DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250907203142_AddPasswordResetToUserFields') THEN
    UPDATE "Usuarios" SET "Descricao" = '' WHERE "Descricao" IS NULL;
    ALTER TABLE "Usuarios" ALTER COLUMN "Descricao" SET NOT NULL;
    ALTER TABLE "Usuarios" ALTER COLUMN "Descricao" SET DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250907203142_AddPasswordResetToUserFields') THEN
    ALTER TABLE "Usuarios" ADD "PasswordResetToken" character varying(255);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250907203142_AddPasswordResetToUserFields') THEN
    ALTER TABLE "Usuarios" ADD "PasswordResetTokenExpires" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250907203142_AddPasswordResetToUserFields') THEN
    UPDATE "Barbearias" SET "Logo" = '' WHERE "Logo" IS NULL;
    ALTER TABLE "Barbearias" ALTER COLUMN "Logo" SET NOT NULL;
    ALTER TABLE "Barbearias" ALTER COLUMN "Logo" SET DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250907203142_AddPasswordResetToUserFields') THEN
    CREATE TABLE "Servicos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" character varying(100) NOT NULL,
        "Preco" numeric(18,2) NOT NULL,
        "DuracaoMinutos" integer NOT NULL,
        "BarbeariaId" integer NOT NULL,
        CONSTRAINT "PK_Servicos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Servicos_Barbearias_BarbeariaId" FOREIGN KEY ("BarbeariaId") REFERENCES "Barbearias" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250907203142_AddPasswordResetToUserFields') THEN
    CREATE INDEX "IX_Servicos_BarbeariaId" ON "Servicos" ("BarbeariaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250907203142_AddPasswordResetToUserFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250907203142_AddPasswordResetToUserFields', '8.0.0');
    END IF;
END $EF$;
COMMIT;

